### PR TITLE
Feature friendship v1

### PR DESCRIPTION
**Pull request by icebox827**
# Milestone  2
- Create friendship model
- Create associations for friendship and user model
- User can invite other user for friend request
- User can accept or reject other user friend request

### CODE REVIEW

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @icebox827 7 @vichuge, 👋🏽 
 **Thank you for the good job you got going on. The app run just fine and almost pass all requirements.**

## REQUIRED CHANGES 🔴 

- [x] When I click on the PENDING FRIENDSHIP, the app breaks giving this error. This is largely because there are no requests initially.
Screensho

- [x] You have a live demo link in your readme file linking to the private events app, You may safely delete that.
- [x] I get the same error as above when I send an invite. Please enable users to send and receive invites.
- [x] Once they receive invites, they should be able to accept or reject the invitation.
- [x] Kindly add unit and integration tests for your app.


**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: APPROACHED🛑🛑🛑**
Hello team,
This is a great implementation of the project.
Great work correcting the previous reviews.
However some few changes are required.

[REQUIRED]: You can only see posts of the people you are friends with.

[REQUIRED]: I saw a bug. When I send the friend request from the user show page and go back to the user index page, there is still an invite button. Kindly fix that.

Kindly make those changes and request for another review👍
Happy coding💻💻💻

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @icebox827 & @vichuge, 👋🏽 
 **Thank you for making the requested changes.** However, there is one more change left as previously explained.

## REQUIRED CHANGES

- [x] When we are already friends and I visit the friend's user index page, the INVITE button still stares blankly 👀, so it creates a never-ending loop sending and accepting the invites.
Screenshot_2021-03-04_03-51-07

- To help you solve this, create a method in the helpers to check if the friendship already exists,  Then place it inside the user index page, this will now determine if the invite button is displayed or not.

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
### Good job Team :+1: for the effort, you have put into this project and implementing the required changes. This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
